# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humitidy', models.FloatField()),
                ('occupancy', models.IntegerField()),
                ('smoke', models.IntegerField()),
            ],
        ),
    ]
