# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20190512_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch', models.BooleanField(default=False, verbose_name='开关')),
            ],
            options={
                'verbose_name': '开关表',
                'verbose_name_plural': '开关表',
            },
        ),
    ]
