# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_roomdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
