# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='温度')),
                ('humidity', models.FloatField(verbose_name='湿度')),
                ('occupancy', models.BooleanField(verbose_name='人体')),
                ('smoke', models.BooleanField(verbose_name='烟')),
            ],
            options={
                'verbose_name': '开关表',
                'verbose_name_plural': '开关表',
            },
        ),
    ]
