# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_device_devicearg_room_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
