# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_scene_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceArg',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='type',
            new_name='device_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='enable',
        ),
        migrations.AddField(
            model_name='device',
            name='arg',
            field=models.FloatField(default=0, verbose_name='参数值'),
        ),
        migrations.AddField(
            model_name='device',
            name='arg_type',
            field=models.IntegerField(default=0, verbose_name='参数类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=0, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
