# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20190506_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='设备id'),
        ),
    ]
