# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_roomdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=50, verbose_name='设备'),
        ),
    ]
