# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20190513_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(verbose_name='aid')),
                ('iid', models.IntegerField(verbose_name='iid')),
                ('type', models.BooleanField(verbose_name='类型')),
                ('allowed', models.IntegerField(verbose_name='允许值')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
            },
        ),
    ]
