# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='服务id'),
            preserve_default=False,
        ),
    ]
