# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_auto_20190519_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlService',
            fields=[
                ('service_id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='服务id')),
                ('aid', models.IntegerField(verbose_name='aid')),
                ('iid', models.IntegerField(verbose_name='iid')),
                ('allowed', models.IntegerField(verbose_name='允许值')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
            ],
            options={
                'verbose_name': '控制服务',
                'verbose_name_plural': '控制服务',
            },
        ),
        migrations.CreateModel(
            name='ReadService',
            fields=[
                ('service_id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='服务id')),
                ('aid', models.IntegerField(verbose_name='aid')),
                ('iid', models.IntegerField(verbose_name='iid')),
                ('allowed', models.IntegerField(verbose_name='允许值')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
            ],
            options={
                'verbose_name': '只读服务',
                'verbose_name_plural': '只读服务',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
