# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20190519_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='action_description',
            field=models.CharField(default=0, max_length=256, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='action_value',
            field=models.BooleanField(default=0, verbose_name='动作值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='control_service_id',
            field=models.IntegerField(default=0, verbose_name='控制服务id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='read_service_id',
            field=models.IntegerField(default=0, verbose_name='只读服务id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='trigger_condition',
            field=models.IntegerField(default=0, verbose_name='触发条件'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='trigger_description',
            field=models.CharField(default=0, max_length=256, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='trigger_value',
            field=models.FloatField(default=0, verbose_name='触发值'),
            preserve_default=False,
        ),
    ]
