# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20190519_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlservice',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readservice',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
