# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20190519_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(verbose_name='设备id')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='数据记录时间')),
            ],
            options={
                'verbose_name': '参数记录',
                'verbose_name_plural': '参数记录',
            },
        ),
    ]
