# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_devicearg'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicearg',
            name='arg',
            field=models.IntegerField(default=0, verbose_name='设备参数'),
        ),
    ]
