# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_devicearg_arg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='controlservice',
            name='description',
            field=models.CharField(default=' ', max_length=256, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='readservice',
            name='description',
            field=models.CharField(default=' ', max_length=256, verbose_name='描述'),
        ),
    ]
